CREATE TABLE TB_TECIDO (
	 PK_ID_TECIDO bigserial not null,
     VAR_ABSORCAO_AGUA_TECIDO varchar(250),
     VAR_COMPORTAMENTO_TERMICO_TECIDO varchar(250),
     VAR_CONSTRUCAO_TECIDO varchar(200),
     VAR_ELASTICIDADE_TECIDO varchar(200),
     VAR_RESISTENCIA_TECIDO varchar(200),
     BOOL_RESPIRAVEL_TECIDO boolean,
     VAR_TEMPO_SECAGEM_TECIDO varchar(200),
     VAR_TIPO_TECIDO varchar(100),
     primary key (PK_ID_TECIDO)
);