ALTER TABLE TB_TECIDO_FIBRA_COMPOSICAO ADD CONSTRAINT FK_ID_FIBRA FOREIGN KEY (FK_ID_FIBRA) REFERENCES TB_FIBRA;

ALTER TABLE TB_TECIDO_FIBRA_COMPOSICAO ADD CONSTRAINT FK_ID_TECIDO FOREIGN KEY (FK_ID_TECIDO) REFERENCES TB_TECIDO;


