INSERT INTO TB_DOM_MANGA
(VAR_COMPRIMENTO_MANGA, VAR_TIPO_MANGA)
VALUES
('regata', 'raglan'),
('regata', 'alcinha'),
('regata', 'muscle tee'),
('regata', 'inteira'),
('curta', 'raglan'),
('curta', 'tulipa'),
('curta', 'bufante'),
('curta', 'com babado'),
('curta', 'vazada'),
('curta', 'gode'),
('curta', 'franzida'),
('curta', 'solta'),
('tres quartos', 'raglan'),
('tres quartos', 'tulipa'),
('tres quartos', 'bufante'),
('tres quartos', 'com babado'),
('tres quartos', 'vazada'),
('tres quartos', 'gode'),
('tres quartos', 'franzida'),
('tres quartos', 'solta'),
('tres quartos', 'sino'),
('longa', 'raglan'),
('longa', 'tulipa'),
('longa', 'bufante'),
('longa', 'com babado'),
('longa', 'vazada'),
('longa', 'gode'),
('longa', 'franzida'),
('longa', 'solta'),
('longa', 'sino'),
('sem', 'sem');
