INSERT INTO TB_DOM_PREGA (VAR_DESCRICAO_PREGA) VALUES ('simples');
INSERT INTO TB_DOM_PREGA (VAR_DESCRICAO_PREGA) VALUES ('femea');
INSERT INTO TB_DOM_PREGA (VAR_DESCRICAO_PREGA) VALUES ('plissado');
INSERT INTO TB_DOM_PREGA (VAR_DESCRICAO_PREGA) VALUES('sem prega');

---MANGA
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('regata raglan'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('regata alcinha'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('regata muscle tee'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('regata inteira'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('curta raglan'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('curta tulipa'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('curta bufante'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('curta com babado'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('curta vazada'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('curta gode'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('curta franzida'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('curta solta'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('tres quartos raglan'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('tres quartos tulipa'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('tres quartos bufante'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('tres quartos com babado'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('tres quartos vazada'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('tres quartos gode'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('tres quartos franzida'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('tres quartos solta'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('tres quartos sino'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('longa raglan'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('longa tulipa'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('longa bufante'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('longa com babado'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('longa vazada'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('longa gode'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('longa franzida'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('longa solta'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('longa sino'); 
INSERT INTO TB_DOM_MANGA (VAR_DESCRICAO_MANGA) VALUES ('sem'); 



-----FIBRA
--------natural
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('natural', 'hidrofilico', 'boa regulacao de calor', 'baixa', 'Algodao', 'moderada', true, 'lento'); 
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('natural', 'hidrofobico', 'boa conservacao de calor', 'baixa', 'Couro', 'alta', false, 'rapido'); 
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('natural', 'hidrofilico', 'boa conservacao de calor', 'alta', 'La', 'alta', true, 'lento'); 
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('natural', 'hidrofobico', 'boa regulacao de calor', 'baixa', 'Linho', 'alta', true, 'rapido'); 
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('natural', 'hidrofilico', 'boa regulacao de calor', 'alta', 'Seda', 'moderada', true, 'lento'); 
--------artificial
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('artificial', 'hidrofobico', 'boa conservacao de calor', 'baixa', 'Acetato', 'moderada', false, 'rapido'); 
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('artificial', 'hidrofilico', 'boa regulacao de calor', 'alta', 'Liocel', 'alta', true, 'rapido'); 
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('artificial', 'hidrofobico', 'boa regulacao de calor', 'alta', 'Modal', 'alta', true, 'rapido'); 
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('artificial', 'hidrofilico', 'boa regulacao de calor', 'baixa', 'Viscose', 'baixa', true, 'lento'); 
-------sintetica
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('sintetica', 'hidrofobico', 'boa regulacao de calor', 'baixa', 'Acrilico', 'alta', true, 'rapido'); 
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('sintetica', 'hidrofobico', 'boa conservacao de calor', 'alta', 'Elastano', 'alta', true, 'rapido'); 
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('sintetica', 'hidrofobico', 'boa regulacao de calor', 'alta', 'Poliamida', 'alta', true, 'rapido'); 
INSERT INTO TB_FIBRA (VAR_TIPO_FIBRA, VAR_ABSORCAO_AGUA_FIBRA, VAR_COMPORTAMENTO_TERMICO_FIBRA, VAR_ELASTICIDADE_FIBRA, VAR_NOME_FIBRA, VAR_RESISTENCIA_FIBRA, BOOL_RESPIRAVEL_FIBRA, VAR_TEMPO_SECAGEM_FIBRA) VALUES ('sintetica', 'hidrofobico', 'boa conservacao de calor', 'alta', 'Poliester', 'alta', false, 'rapido'); 


-------FECHAMENTO
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('ziper lateral'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('ziper frente'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('ziper costas'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('botao lateral'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('botao costas'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('botao frente'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('colchete costas'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('colchete lateral'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('colchete frente'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('fita costas'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('fita lateral'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('fita frente'); 
INSERT INTO TB_DOM_FECHAMENTO (VAR_DESCRICAO_FECHAMENTO) VALUES ('sem'); 


--------DECOTE
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('canoa'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('gola alta'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('tomara que caia'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('v'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('u'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('quadrado'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('careca'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('colarinho ingles'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('colarinho americano'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('colarinho italiano'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('colarinho curto'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('colarinho mao'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('colarinho opera'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('colarinho quebrado'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('lapela xale'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('lapela quadrada'); 
INSERT INTO TB_DOM_DECOTE (VAR_DESCRICAO_DECOTE) VALUES ('lapela pontuda'); 

------BARRA
INSERT INTO TB_DOM_BARRA (VAR_DESCRICAO_BARRA) VALUES ('invisivel'); 
INSERT INTO TB_DOM_BARRA (VAR_DESCRICAO_BARRA) VALUES ('lenco'); 
INSERT INTO TB_DOM_BARRA (VAR_DESCRICAO_BARRA) VALUES ('italiana'); 
INSERT INTO TB_DOM_BARRA (VAR_DESCRICAO_BARRA) VALUES ('simples'); 
INSERT INTO TB_DOM_BARRA (VAR_DESCRICAO_BARRA) VALUES ('galoneira'); 
INSERT INTO TB_DOM_BARRA (VAR_DESCRICAO_BARRA) VALUES ('vies'); 
INSERT INTO TB_DOM_BARRA (VAR_DESCRICAO_BARRA) VALUES ('desfiada'); 

------TIPOROUPA
INSERT INTO TB_DOM_TIPO_ROUPA (VAR_DESCRICAO_TIPO_ROUPA) VALUES ('top'); 
INSERT INTO TB_DOM_TIPO_ROUPA (VAR_DESCRICAO_TIPO_ROUPA) VALUES ('camiseta'); 
INSERT INTO TB_DOM_TIPO_ROUPA (VAR_DESCRICAO_TIPO_ROUPA) VALUES ('blusa'); 
INSERT INTO TB_DOM_TIPO_ROUPA (VAR_DESCRICAO_TIPO_ROUPA) VALUES ('camisa'); 
INSERT INTO TB_DOM_TIPO_ROUPA (VAR_DESCRICAO_TIPO_ROUPA) VALUES ('colete'); 
INSERT INTO TB_DOM_TIPO_ROUPA (VAR_DESCRICAO_TIPO_ROUPA) VALUES ('poncho'); 
INSERT INTO TB_DOM_TIPO_ROUPA (VAR_DESCRICAO_TIPO_ROUPA) VALUES ('casaco'); 
INSERT INTO TB_DOM_TIPO_ROUPA (VAR_DESCRICAO_TIPO_ROUPA) VALUES ('jaqueta'); 
INSERT INTO TB_DOM_TIPO_ROUPA (VAR_DESCRICAO_TIPO_ROUPA) VALUES ('blazer');


----SILHUETA
INSERT INTO TB_DOM_SILHUETA (VAR_DESCRICAO_SILHUETA) VALUES ('justa'); 
INSERT INTO TB_DOM_SILHUETA (VAR_DESCRICAO_SILHUETA) VALUES ('reta'); 
INSERT INTO TB_DOM_SILHUETA (VAR_DESCRICAO_SILHUETA) VALUES ('larga'); 

------CAVA
INSERT INTO TB_DOM_CAVA (VAR_DESCRICAO_CAVA) VALUES ('justa'); 
INSERT INTO TB_DOM_CAVA (VAR_DESCRICAO_CAVA) VALUES ('baixa'); 
INSERT INTO TB_DOM_CAVA (VAR_DESCRICAO_CAVA) VALUES ('sem'); 


-----COMPRIMENTO
INSERT INTO TB_DOM_COMPRIMENTO (VAR_DESCRICAO_COMPRIMENTO) VALUES ('cropped');  
INSERT INTO TB_DOM_COMPRIMENTO (VAR_DESCRICAO_COMPRIMENTO) VALUES ('cintura'); 
INSERT INTO TB_DOM_COMPRIMENTO (VAR_DESCRICAO_COMPRIMENTO) VALUES ('quadril'); 
INSERT INTO TB_DOM_COMPRIMENTO (VAR_DESCRICAO_COMPRIMENTO) VALUES ('torax'); 
INSERT INTO TB_DOM_COMPRIMENTO (VAR_DESCRICAO_COMPRIMENTO) VALUES ('abaixo do quadril'); 


--- para casacos
INSERT INTO TB_DOM_COMPRIMENTO (VAR_DESCRICAO_COMPRIMENTO) VALUES ('meio da coxa'); 
INSERT INTO TB_DOM_COMPRIMENTO (VAR_DESCRICAO_COMPRIMENTO) VALUES ('joelho'); 
INSERT INTO TB_DOM_COMPRIMENTO (VAR_DESCRICAO_COMPRIMENTO) VALUES ('abaixo do joelho'); 
INSERT INTO TB_DOM_COMPRIMENTO (VAR_DESCRICAO_COMPRIMENTO) VALUES ('meio da canela'); 
INSERT INTO TB_DOM_COMPRIMENTO (VAR_DESCRICAO_COMPRIMENTO) VALUES ('tornozelo'); 

