ALTER TABLE TB_ROUPA ADD CONSTRAINT FK_ID_SILHUETA FOREIGN KEY (FK_ID_SILHUETA) REFERENCES TB_DOM_SILHUETA;

ALTER TABLE TB_ROUPA ADD CONSTRAINT FK_ID_FECHAMENTO FOREIGN KEY (FK_ID_FECHAMENTO) REFERENCES TB_DOM_FECHAMENTO;

ALTER TABLE TB_ROUPA ADD CONSTRAINT FK_ID_PREGA FOREIGN KEY (FK_ID_PREGA) REFERENCES TB_DOM_PREGA;

ALTER TABLE TB_ROUPA ADD CONSTRAINT FK_ID_BARRA FOREIGN KEY (FK_ID_BARRA) REFERENCES TB_DOM_BARRA;

ALTER TABLE TB_ROUPA ADD CONSTRAINT FK_ID_TECIDO FOREIGN KEY (FK_ID_TECIDO) REFERENCES TB_TECIDO;

ALTER TABLE TB_ROUPA ADD CONSTRAINT FK_ID_DECOTE FOREIGN KEY (FK_ID_DECOTE) REFERENCES TB_DOM_DECOTE;

ALTER TABLE TB_ROUPA ADD CONSTRAINT FK_ID_MANGA FOREIGN KEY (FK_ID_MANGA) REFERENCES TB_DOM_MANGA;

ALTER TABLE TB_ROUPA ADD CONSTRAINT FK_ID_CAVA FOREIGN KEY (FK_ID_CAVA) REFERENCES TB_DOM_CAVA;

ALTER TABLE TB_ROUPA ADD CONSTRAINT FK_ID_COMPRIMENTO FOREIGN KEY (FK_ID_COMPRIMENTO) REFERENCES TB_DOM_COMPRIMENTO;